function MAF_key = import_MAF_key(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HTMNYCMAFDATAEARLYRELEASE = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a
%  string array.
%
%  HTMNYCMAFDATAEARLYRELEASE = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MAF_key = import_MAF_key("/Users/poeppellab/Downloads/HtM NYC_MAF Data_Early Release.csv", [1, 1]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Sep-2019 16:56:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["JobCode", "Aircraft", "TransactionCode", "MalfunctionCode", "ActionTakenCode", "DescriptionofProblem", "CorrectionofProblem", "ReceivedDate", "CompletionDate", "Corrosion", "BareMetal", "CorrosionPreventionTreatment", "RoutineMaintenance", "UnscheduledMaintenance", "MissionRelatedMaintenance", "Failure"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
MAF_key = readtable(filename, opts);

%% Convert to output type
MAF_key = table2array(MAF_key);
end